name: Deployment Flow
concurrency: deployment-flow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Next.js dependencies
        run: npm install
        working-directory: frontend-app
          

      - name: Build Next.js application as static website
        run: npm run build
        working-directory: frontend-app          

  deploy-to-dev:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: Development

    steps:
      - uses: actions/checkout@v4

      - name: Install Next.js dependencies
        run: npm install
        working-directory: frontend-app

      - name: Build Next.js application as static website
        run: npm run build
        working-directory: frontend-app