name: Deploy To Environment

on:
  workflow_call:
    inputs:         
      ENVIRONMENT:
        required: true
        type: string
      SITE_STACK_NAME:
        required: true
        type: string
      SITE_SUB_DOMAIN:
        required: true
        type: string
      ALLOWED_IP_SET:
        type: string
    secrets:
      AWS_ACCESS_KEY:
        required: true
      AWS_SECRET_KEY:
        required: true
      CDK_DEFAULT_ACCOUNT:
        required: true        

jobs:
  deploy-infrastructure:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
  
    steps:
      - uses: actions/checkout@v4

      - name: Install Next.js dependencies
        run: npm install
        working-directory: frontend-app

      - name: Build Next App for environment
        run: npm run build
        working-directory: frontend-app

      - name: Install AWS CDK dependencies
        run: npm install
        working-directory: infrastructure

      - name: Creating / Updating Infrastructure
        uses: youyo/aws-cdk-github-actions@v2
        with:
          cdk_subcommand: 'deploy'
          cdk_stack: ${{ vars.SITE_STACK_NAME }}
          cdk_args: '--parameters subDomainName=${{ vars.SITE_SUB_DOMAIN }} --parameters allowedIPSet=${{ vars.ALLOWED_IP_SET }} --require-approval never'
          working_dir: 'infrastructure'
          actions_comment: false
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
          CDK_DEFAULT_ACCOUNT: ${{ secrets.CDK_DEFAULT_ACCOUNT }}