name: Deployment Pipeline
concurrency: deployment-pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy-to-dev:    
    uses: ./.github/workflows/deploy-to-environment.yml
    with:
      siteStackName: test-a
      awsCDKRegion: test-b
      siteSubDomain: test-c
    secrets:
      awsAccessKey: test-d
      awsSecretKey: test-e
