name: Deploy To Environment

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      # site_stack_name:
      #   description: The name of the AWS Stack to deploy
      #   required: true
      #   type: string
      # aws_cdk_region:
      #   description: The region to deploy the AWS Stack to
      #   required: true
      #   type: string
      # site_sub_domain:
      #   description: The sub domain name for this deployment
      #   required: true
      #   type: string
    secrets:
      aws_access_key:
        description: The AWS access key that represents the AWS Account needed to run this deployment
        required: true
      aws_secret_key:
        description: The AWS secret key that represents the AWS Account needed to run this deployment
        required: true

jobs:
  deploy-infrastructure:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
  
    steps:
      - name: Print out variables
        run: echo ${{ inputs.SITE_SUB_DOMAIN }}

      - uses: actions/checkout@v4

      - name: Install Next.js dependencies
        run: npm install
        working-directory: frontend-app

      - name: Build Next App for environment
        run: npm run build
        working-directory: frontend-app

      - name: Install AWS CDK dependencies
        run: npm install
        working-directory: infrastructure

      - name: Creating / Updating Infrastructure
        uses: youyo/aws-cdk-github-actions@v2
        with:
          cdk_subcommand: 'deploy'
          cdk_stack: ${{ inputs.site_stack_name }}
          cdk_args: '--parameters subDomainName=${{ inputs.site_sub_domain }} --require-approval never'
          working_dir: 'infrastructure'
          actions_comment: false
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.aws_access_key }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.aws_secret_key }}
          AWS_DEFAULT_REGION: ${{ inputs.aws_cdk_region }} 