name: Deployment Pipeline
concurrency: deployment-pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy-to-dev:    
    uses: ./.github/workflows/deploy-to-environment.yml
    secrets:
      token: "${{ secrets.AWS_ACCESS_KEY }}"
