name: Deployment Pipeline
concurrency: deployment-pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy-to-dev:
    environment: Development
    runs-on: ubuntu-latest

    steps:
      - name: Deploying to Development Environment
        uses: ./.github/workflows/deploy-to-environment.yml
        with:
          environment: Development