name: Deploy To Environment

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

jobs:
  deploy-infrastructure:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
  
    steps:
      - name: Print out variables
        run: |
          echo AWS_ACCESS_KEY is ${{ vars.AWS_ACCESS_KEY }}
          echo AWS_SECRET_KEY is ${{ vars.AWS_SECRET_KEY }}
          echo CDK_DEFAULT_REGION is ${{ vars.CDK_DEFAULT_REGION }}
          echo CDK_DEFAULT_ACCOUNT is ${{ vars.CDK_DEFAULT_ACCOUNT }}
          echo secrets is ${{ secrets }}

      - uses: actions/checkout@v4

      - name: Install Next.js dependencies
        run: npm install
        working-directory: frontend-app

      - name: Build Next App for environment
        run: npm run build
        working-directory: frontend-app

      - name: Install AWS CDK dependencies
        run: npm install
        working-directory: infrastructure

      - name: Creating / Updating Infrastructure
        uses: youyo/aws-cdk-github-actions@v2
        with:
          cdk_subcommand: 'deploy'
          cdk_stack: ${{ vars.SITE_STACK_NAME }}
          cdk_args: '--parameters subDomainName=${{ vars.SITE_SUB_DOMAIN }} --require-approval never'
          working_dir: 'infrastructure'
          actions_comment: false
        env:
          AWS_ACCESS_KEY_ID: ${{ vars.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ vars.AWS_SECRET_KEY }}
          AWS_DEFAULT_REGION: ${{ vars.CDK_DEFAULT_REGION }}
          CDK_DEFAULT_ACCOUNT: ${{ vars.CDK_DEFAULT_ACCOUNT }}