name: Deployment Pipeline
concurrency: deployment-pipeline

on:
  push:
    branches:
      - main

jobs:
  prepare-code:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

      - name: Install Next.js dependencies
        run: npm install
        working-directory: frontend-app

      - name: Upload dependencies as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: next-app-node-modules
          path: frontend-app/node_modules

  # deploy-to-dev:
  #   needs: prepare-code
  #   uses: ./.github/workflows/deployment.yml
