name: Deployment Pipeline
concurrency: deployment-pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy-to-dev:
    runs-on: ubuntu-latest
    environment: Development

    steps:
      - name: Deploying to Development Environment
        uses: ./.github/workflows/deploy-to-environment.yml
        with:
          AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_KEY: ${{ vars.AWS_SECRET_KEY }}
          CDK_DEFAULT_REGION: ${{ vars.CDK_DEFAULT_REGION }}
          CDK_DEFAULT_ACCOUNT: ${{ vars.CDK_DEFAULT_ACCOUNT }}