import clsx from "clsx";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { useState } from "react";

import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const layoutClasses = clsx(
    inter.className,
    "dark:bg-stone-900"
  );

  return (
    <html lang="en">
      <body className={layoutClasses}>{children}</body>
    </html>
  );
}
